<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250719111003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE organizations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, regon VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_427C1C7F4C3FA511 ON organizations (regon)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_427C1C7FE7927C74 ON organizations (email)');
        $this->addSql('ALTER TABLE users ADD organization_id INT NOT NULL');
        $this->addSql('ALTER TABLE users ALTER first_name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE users ALTER first_name SET NOT NULL');
        $this->addSql('ALTER TABLE users ALTER last_name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE users ALTER last_name SET NOT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E932C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_1483A5E932C8A3DE ON users (organization_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE organizations');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E932C8A3DE');
        $this->addSql('DROP INDEX IDX_1483A5E932C8A3DE');
        $this->addSql('ALTER TABLE users DROP organization_id');
        $this->addSql('ALTER TABLE users ALTER first_name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE users ALTER first_name DROP NOT NULL');
        $this->addSql('ALTER TABLE users ALTER last_name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE users ALTER last_name DROP NOT NULL');
    }
}
